language: generic
branches:
  only:
    - master
env:
  DEV_REGISTRY=quay.io
cache:
  directories:
    - vendor
services:
  - docker
sudo: required
install:
  - make bootstrap
script:
  - make build test dist prep-bintray-json
deploy:
  - provider: bintray
    # ensure client/doc builds aren't removed
    # see https://docs.travis-ci.com/user/deployment/#Uploading-Files
    skip_cleanup: true
    file: _scripts/ci/bintray-ci.json
    user: deis-admin
    key:
      secure: "JVCyPvXZIabZBhWgZ2wX4UDoTpIAjVnp+Ox6cXywYbACzKZSTz6G1kFcItzpUiEygUtye1213Zb+2050jq3BK7wohy5lcZCDJgrhyw6RxTRWIQQ5o+pS+O/AOYCSbpPn2E5goNutAhlOVsf2TlXkt4wz0jl5qOaecm0QXoiXBPUH5H1a3ifnCylybVG2jc2Kj/9S5uMGDQqocrPTXedZo9E/Es61MbKttlJGfcIrjbS71J8QZvDTcTSjzGT5CVdQulzkLNmFI5y31XwBE9XC6ro/Can10bIvy6yzYSWraUBTXVLWY2mPrPSlohOqNiYg2goQFQ2KwAGe6mVbq3UqOrYqNLXDdpSnCsRkx2KBw+ifET+0neq1NI3v5oSjKZ+p2zKCWQoOxahU40Eg+hA12oN17yHglaj2PGLuxYicDc+BQEGcGdBHAPJNXALd+rSDCdq5Gnd9HsCQE2Tyc+YK2bKvfpgcQNLS7gtiIxoRLZ1/qRBq3SB3IyQik7jjPe9Y0Meqnmdk8PeXM113/MSGdqZtVfyaOcT8SPgN22dhV42fs/BQtplTT3Hcs3yhmDwtl1w1udynerHcWx0PqZFn3h95SozJFPi8UdsbZog5V/CY/OAFs3K4bm3ay4Re1r2vTFCRuukp6UwtT5QR4kjsKWrLkewFbjId2FazJA8kMc4="
    on:
      branch: master
notifications:
  webhooks:
    urls:
      - secure: "Kirwb8QgjbctztB/ze89XmrukN/1tS8Vb3ZVrAidusVJdHakiEJbbSDTnMuDcLwY+MXZfMM1zRDpXOnbG4QKOUjh1ytPCY9cKsbSuQ3oH+siCJk2oFtIDcs35hp5iNSq+B4YjttexSKOR2opNXkGuTHoVPVb6t10JIXPLuL3YCphlvCTWzLb5aV/yHHaIalkZV//5E+gmvOzUEYrS1/d+Hrp0yFoD9zH1ze+kIRTx6RiXTwG/Y6Z3e5PH2Jpygv37rNCiedE4CtQGR3sjashzciU7f5WZpMaTdhUdOY3vHFzq0Zz6iZb1jbzFdnUsPjHsG6e8zqh7p4XVrct1RGecd40tTcYXbohSX0izujvqSzFMqb/Chh5jrad6quo8tlTLTcldSIdCP3lSJolod4x9SWewGQAXJ0+w7yiBTyA+vTLHQEYD8xrWbkwk8KLjfwLGuDwW9ijvhci5hV9w/cEO0L0pjCaLUftmbol6ZIcuX2lxBAm8QnNoYgH5B8uI6pxzIZ9i1wGtszPBB/9qCKtTV8hy2L0rrCeOUqyigcbASuoJ1naah7nn2xeD5zvaTe9jhVJrIxpbiWxfjGxzhz7h4UL8OsnQAXL/yFcesixLIKqwkSRNP0GAHBTQFb8yzTicFThqsnb8hsXardTCZJ2M2ohf6bGhx0ujE/Cjg+X0lk="
    on_success: always
    on_failure: never
    on_start: never
