language: generic
branches:
  only:
  - master
cache:
  directories:
  - vendor
services:
- docker
sudo: required
install:
- make bootstrap
script:
- make build test dist prep-bintray-json
deploy:
  provider: bintray
  skip_cleanup: true
  file: _scripts/ci/bintray-ci.json
  user: deis-admin
  key:
    secure: ebRnLiUjD5fJXRpqTeYcNOea4B9wO/GlCGO5v5MSlivn6FnZREkn/yygZdS07EPizOQXxXb0yZqzZdLdVtumknRtVSU/RyIU8Wo3kG6vCm6wkH9VIhfg7PUc31bUXKpN3GZTmMeEyGZ+OQvZ9voSArHNeSRWLKfGjP4qpiJGx5wL1bTpZs3gL+n8+APypKPXYh290/RWHXW/RcZzUHLVE/f18gT7IfiUUG2PznMS9JkUz8yZ/f+hf9QUWPvjtm4vdjuOZ0EhBAaVy+pcBXmfcz9f2ZgwleV/qteCpp0hDBGMAbVDAUydTzzxmpjyFuoU5/etrsuUjlsUVASED25YMUaWSMOGBl0wZVxxi/FlXgwTuTv4Idu58CM62EjIQnnLd6PpscYSqQ1scQK4C4qLQElPyGcGTpPJSQ7n5vxVminIpfrRoDRBU3zrkFL3Z4nEQLpexHl5OhZVbB7nktzYAvzBDsl8d6aNRxuVBcviF1VDxSc/8axneXmDxzDm5QROw6sfBtAJlad+u1AjvfptPLG6TOwwQRCSvChIDkCLRJlGVdpJn1hP3ccDuS4VDU+T/NJzeeZ6tR5I8mrSbYucaj5WOB6Xfi9DXIX3HYFHm8PJAgO+1v9/Dlk7KqYk1aokNkRLF+/6m51LR/pYGIcuH3AJdXYIjv1x7jM824dFkGw=
  on:
    branch: master
notifications:
  webhooks:
    urls:
    - secure: Kirwb8QgjbctztB/ze89XmrukN/1tS8Vb3ZVrAidusVJdHakiEJbbSDTnMuDcLwY+MXZfMM1zRDpXOnbG4QKOUjh1ytPCY9cKsbSuQ3oH+siCJk2oFtIDcs35hp5iNSq+B4YjttexSKOR2opNXkGuTHoVPVb6t10JIXPLuL3YCphlvCTWzLb5aV/yHHaIalkZV//5E+gmvOzUEYrS1/d+Hrp0yFoD9zH1ze+kIRTx6RiXTwG/Y6Z3e5PH2Jpygv37rNCiedE4CtQGR3sjashzciU7f5WZpMaTdhUdOY3vHFzq0Zz6iZb1jbzFdnUsPjHsG6e8zqh7p4XVrct1RGecd40tTcYXbohSX0izujvqSzFMqb/Chh5jrad6quo8tlTLTcldSIdCP3lSJolod4x9SWewGQAXJ0+w7yiBTyA+vTLHQEYD8xrWbkwk8KLjfwLGuDwW9ijvhci5hV9w/cEO0L0pjCaLUftmbol6ZIcuX2lxBAm8QnNoYgH5B8uI6pxzIZ9i1wGtszPBB/9qCKtTV8hy2L0rrCeOUqyigcbASuoJ1naah7nn2xeD5zvaTe9jhVJrIxpbiWxfjGxzhz7h4UL8OsnQAXL/yFcesixLIKqwkSRNP0GAHBTQFb8yzTicFThqsnb8hsXardTCZJ2M2ohf6bGhx0ujE/Cjg+X0lk=
    on_success: always
    on_failure: never
    on_start: never
